services:

  mongodb:
    image: mongo:7.0.5
    container_name: rag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"           
    volumes:
      -  ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mongodb:/var/lib/mongodb/data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


  qdrant:
    image: qdrant/qdrant:v1.17
    container_name: rag-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"             
      - "6334:6334"             
    volumes:
      -  ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/6333' 2>/dev/null && echo ok || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  ollama:
    image: ollama/ollama:0.20.7
    container_name: rag-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      -  ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/ollama_data:/ollama/data
      - ./backend/scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/ollama_entrypoint.sh"]

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility


  backend:
    image: ${DOCKER_USERNAME:-chianh12}/rag-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_URL:      mongodb://mongodb:27017
      QDRANT_URL:       http://qdrant:6333
      OLLAMA_BASE_URL:  http://ollama:11434
      OLLAMA_CHAT_MODEL: ${OLLAMA_CHAT_MODEL:-qwen3.5:4b}
      OLLAMA_EMBEDDINGS_MODEL: ${OLLAMA_EMBEDDINGS_MODEL:-nomic-embed-text:latest}
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mineru_models:/root/.cache/huggingface
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/md_cache:/app/md_cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mongodb:
        condition: service_healthy
      qdrant:
        condition: service_healthy

    

  frontend:
    image: ${DOCKER_USERNAME:-chianh12}/rag-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: /api   # nginx proxy /api → backend:8000
    container_name: rag-frontend
    restart: unless-stopped
    ports:
      - "3000:80"               
    depends_on:
      - backend

networks:
  default:
    name: rag-network
